client clab-net {
    # データ網全体を許可（NASの送信元がユーザ網/サービス網どちらでも受理）
    ipaddr = 10.1.0.0/16
    secret = labpassword
    shortname = clab
    nas_type = other
}
client clab-mgmt {
    ipaddr = 172.16.0.0/12
    secret = labpassword
    shortname = clab-mgmt
}
